config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :posts, only: [:show, :index]
  end
  resources :categories
  resources :users
  resources :posts do
    resources :comments, only: [:create, :new, :index, :destroy]
    resources :categories, only: [:index, :show]
  end
  root 'posts#index'
  get   '/signup', to: 'user#new'
  get   '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'
  get '/logout', to: 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  # belongs_to :category
end

app/controllers/posts_controller.rb
require 'redcarpet'

class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @user = current_user
    renderer = Redcarpet::Render::HTML.new(fenced_code_blocks: true, autolink: true, quote: true)
    markdown = Redcarpet::Markdown.new(renderer, extensions = {})

  end

  # GET /posts/1
  # GET /posts/1.json
  def show

  end

  # GET /posts/new
  def new
    @post = Post.new
    @user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    # @post.category_id = params[:post][:category_id].to_i

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, notice: 'Didnt work' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :created, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="titlefield">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="datefield">
    <%= form.label :created %>
    <%= form.text_field :created %>
  </div>

  <div class="textfield">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div

<br></br>

    <div class="submit">
      <%= form.submit %>
    </div>

<% end %>

app/views/posts/_hammenuandtop.html.erb
<button id="hamburger">&#9776;</button>
<div class="nav"><%= render 'navlinks'%><a href="" id="cross">&#735;</a></div>


<div class="top">
  <button id="top">&#8593;</button>
</div>

app/views/posts/_navlinks.html.erb
<% if current_user %>
  <% if current_user.name == "Emily" %>
    <%= link_to 'New Post', new_post_path %>
    <%= link_to "Log out", logout_path, method: :delete %>
    <%= link_to "Log In", login_path%>
  <%end%>
<%end%>
<%= link_to "All Posts", posts_path%>
<%= link_to "About Emily", 'https://www.this-is-emily.com'%>
<%= link_to "Projects", 'https://www.this-is-emily.com/projects'%>
<%= link_to "Contact", 'https://www.this-is-emily.com/contact'%>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

  <%= render 'form', post: @post %>


<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="noticemessage"><%= notice %></div>

<h3 class="blogsubtitle">Emily's Blog</h3>

<h1 class="blogtitle">'Usual' is Boring</h1>

<hr></hr>

<div class="allposts">
  <% @posts.sort_by{|post| post.created }.reverse.each do |post| %>

    <div class="postcard">
      <div class="post-title"><%= post.title %></div>
      <div class="created"><%= convert_date(post.created) %></div>
      <div class="post-preview">
        <%=link_to(post) do %>
          <%= postcontent(post.content.truncate(160)) %>
        <%end%>
      </div>

      <div class="actionscontainer">
        <div class="actions"><%= link_to 'Read More...', post %></div>
        <div class="comments"><%= link_to post.comments.count, post_comments_path(post)%> <%= link_to 'comment(s)', post_comments_path(post)%></div>
      </div>
    </div>

  <% end %>

  <button id="hamburger">&#9776;</button>
  <div class="nav"><%= render 'navlinks'%><a href="" id="cross">&#735;</a></div>


  <div class="top">
    <button id="top">&#8593;</button>
  </div>

</div>

app/views/posts/new.html.erb
<div class="post-body">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="blogtitle">
  <%= @post.title %>
</div>

<div class="blogsubtitle" id="creator">
    by <%= @post.user.name %>
</div>

<div class="blogsubtitle">
    <%= convert_date(@post.created) %>
</div>

<div class="show_post">
  <%= postcontent(@post.content) %>
</div>



<div class="footer">

<% if current_user %>
  <% if current_user.name == "Emily" %>
    <div className="actions-show-box">
    <div class="actions_show"><%= link_to 'Edit', edit_post_path %></div>
    <div class="actions_show"><%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %></div>
  <%end%>
<%end%>
    <div class="actions_show"><%= link_to 'Back to Posts', posts_path %></div>
    <div class="actions_show"><%= link_to 'Post a Comment', new_post_comment_path(@post) %></div>
  </div>


  <br></br>
  <div class="post-comments">
    <%= link_to @post.comments.count, post_comments_path(@post)%> <%= link_to 'comment(s):', post_comments_path(@post)%>
  </div>

  <% @post.comments.each do |comment| %>
    <div class="comment-wrapper">
      <div class="commenter">Posted by: <%= comment.name %></div>
      <div class="comment-text"><%= comment.content %></div>
    </div>
  <% end %>

</div>


<button id="hamburger">&#9776;</button>
<div class="nav"><%= render 'navlinks'%><a href="" id="cross">&#735;</a></div>