config/routes.rb
Rails.application.routes.draw do
  resources :categories do
    resources :posts, only: [:show, :index]
  end
  resources :categories
  resources :users
  resources :posts do
    resources :comments, only: [:create, :new, :index, :destroy]
    resources :categories, only: [:index, :show]
  end
  root 'posts#index'
  get   '/signup', to: 'user#new'
  get   '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'
  get '/logout', to: 'session#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(id: params[:id])
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>

<% @categories.each do |cat| %>

    <p id="smaller"><%=link_to cat.title , category_path(cat)%> (<%=cat.posts.count%>)</p>

<% end %>

<button id="hamburger">&#9776;</button>
<div class="nav"><%= render 'posts/navlinks'%><a href="" id="cross">&#735;</a></div>


<div class="top">
  <button id="top">&#8593;</button>
</div>

app/views/categories/show.html.erb
<h1>Categories > <%=@category.title%></h1>

<h1 class="blogtitle">Posts about <%=@category.title%></h1>

<%if @category.posts.empty?%>
  <h2 class="blogsubtitle"> No Posts in this category yet.</h2>
<%else%>
  <%@category.posts.each do |c|%>
    <p id="smaller">
      <%=link_to c.title, post_path(c)%><br>
      <%=c.created%>
    </p>
  <%end%>
<%end%>

<button id="hamburger">&#9776;</button>
<div class="nav"><%= render 'posts/navlinks'%><a href="" id="cross">&#735;</a></div>


<div class="top">
  <button id="top">&#8593;</button>
</div>